name: Build and Cache .NET Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            publish_runtime: linux-x64
          - os: windows-latest 
            publish_runtime: win-x64
          - os: macos-latest
            publish_runtime: osx-x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish
      run: dotnet publish -c Release -r ${{ matrix.publish_runtime }} --self-contained true -p:PublishSingleFile=true -o ./publish

    - name: Cache published artifacts  
      uses: actions/cache@v3
      with:
        path: ./publish
        key: ${{ runner.os }}-publish-${{ github.sha }}
