name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers when you push a tag starting with 'v'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # Build for Linux and Windows
        dotnet-version: ['9.0.x'] # Specify your target .NET version

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release

      - name: Publish Binaries
        run: dotnet publish --configuration Release --runtime ${{ matrix.os == 'ubuntu-latest' && 'linux-x64' || 'win-x64' }} --self-contained -p:PublishSingleFile=true
        env:
          DOTNET_ROOT: ${{ env.DOTNET_ROOT }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Sidecar-v3-${{ matrix.os }}
          path: |
            **/bin/Release/net*/publish/
            !**/*.pdb
