name: Build and Cache .NET Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            publish_runtime: linux-x64
          - os: windows-latest 
            publish_runtime: win-x64
          - os: macos-latest
            publish_runtime: osx-x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore cached published artifacts
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ./publish
        key: ${{ runner.os }}-publish-${{ github.sha }}

    - name: Restore dependencies
      if: steps.cache-restore.outputs.cache-hit != 'true'  
      run: dotnet restore

    - name: Build
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: dotnet publish -c Release -r ${{ matrix.publish_runtime }} --self-contained true -p:PublishSingleFile=true -o ./publish

    - name: Cache published artifacts
      id: cache-save  
      uses: actions/cache/save@v4
      with:
        path: ./publish
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }}-artifact
        path: ./publish/*
